### ISSUE TITLE
Wrong manifest files

### ISSUE THREAD

**Issue by KarolAntczak** [Samsung/Dexter#37]
Manifest files from [project-name]/META-INF/MANIFEST.MF aren't copied properly. As a result, manifest files in jars are wrong. 

For example:

**dexter-executor/META-INF/MANIFEST.MF:**

    Manifest-Version: 1.0
    Bundle-ManifestVersion: 2
    BUndle-RequiredExecutionEnvironment: JavaSE-1.7
    Bundle-Name: Dexter Executor
    Bundle-SymbolicName: dexter-core;singleton:=true
    Bundle-Version: 0.9.2
     ... 

**dexter-executor.jar/META-INF/MANIFEST.MF:**

    Manifest-Version: 1.0
    Ant-Version: Apache Ant 1.9.4
    Created-By: 1.8.0_65-b17 (Oracle Corporation)
    Main-Class: com.samsung.sec.dexter.executor.cli.Main
    Class-Path: .

**Comment by Min-Ho-Kim** [comment]
Hi, 

Thank you for the report.
This is because we use two build tools: Eclipse Plugin Export and Ant tool.

With Eclipse Plugin Export, the jar file will be used in a Eclipse Platform (RCP or Plugins).
With Ant tool, the jar file will be used by java command as Dexter CLI.
for example, java -jar -XX:MaxPermSize=256m dexter-executor.jar

So, the first example that you mentioned is for Eclipse Platform
and the second one is for Dexter CLI.

**Comment by KarolAntczak** [comment]
Oh, I see. Thanks for the explanation.
